import { Game, Profile } from "structs.slint";
import { Tabs } from "main/tabs.slint";
import { Menu } from "main/menu.slint";
import { Actions } from "main/actions.slint";

export component MainWindow inherits Window {
    preferred-width: 1920px;
    preferred-height: 1080px;
    icon: @image-url("../resources/obliteration-icon.png");
    title: "Obliteration";

    in property <[Game]> games: [];
    in property <[Profile]> profiles: [];
    in property <[string]> devices: [];

    pure callback start_game(Game);

    pure callback clear_log();
    pure callback get_log_text() -> string;

    pure callback open_new_issue_link();

    pure callback install_pkg();
    pure callback open_system_folder();
    pure callback quit();

    VerticalLayout {
        Menu {
            background: root.background;
            popup_width: root.width / 2;
            popup_height: root.height / 2;
            popup_x: root.width / 4;
            popup_y: root.height / 4;

            quit => { quit(); }
            open_new_issue_link => { open_new_issue_link(); }
            install_pkg => { install_pkg(); }
            open_system_folder => { open_system_folder(); }
        }
        Tabs {
            devices: devices;
            games: games;
            select_game(index) => {  }
        }
        Actions {
            start_game => {}
        }
    }
}
