import { ComboBox, Button } from "std-widgets.slint";

export component Actions {
    pure callback start_game();

    HorizontalLayout {
        alignment: stretch;
        spacing: 5px;

        ComboBox {
            model: ["Default"];
            horizontal-stretch: 1;
        }
        Button {
            text: "Start";
            horizontal-stretch: 0;
            icon: @image-url("../../resources/play.svg");
            clicked => { start_game(); }
        }
        Button {
            text: "Save";
            horizontal-stretch: 0;
            icon: @image-url("../../resources/content-save.svg");
        }
    }
}
