import { Button, ComboBox, HorizontalBox } from "std-widgets.slint";

export component Actions {
    in property <[string]> profiles: [];

    pure callback start_game();

    HorizontalBox {
        ComboBox {
            model: profiles;
            horizontal-stretch: 1;
        }

        Button {
            text: "Start";
            icon: @image-url("../../resources/play.svg");
            clicked => { start_game(); }
        }

        Button {
            text: "Save";
            icon: @image-url("../../resources/content-save.svg");
        }
    }
}
