import { Button, StandardButton, AboutSlint, HorizontalBox, Palette, VerticalBox } from "std-widgets.slint";
import { Globals } from "../globals.slint";

component MenuItem inherits Rectangle {
    background: Palette.background;

    in property <string> title;

    Button {
        text: title;
        clicked => {
            submenu.show();
        }
    }

    submenu := PopupWindow {
        x: parent.x + parent.width;

        VerticalLayout {
            spacing: 0;

            @children
        }
    }
}

component BaseDialog inherits PopupWindow {
    Rectangle {
        background: Palette.background;

        VerticalBox {
            @children

            HorizontalBox {
                StandardButton {
                    kind: ok;
                }
            }
        }
    }
}

component AboutDialog inherits BaseDialog {
    Text {
        text: "Obliteration is a free and open-source software for playing your PlayStation 4 titles on PC.";
    }
}

component LogsDialog inherits BaseDialog { }

export component Menu {
    in property <length> popup_width;
    in property <length> popup_height;
    in property <length> popup_x;
    in property <length> popup_y;

    pure callback quit();
    pure callback open_new_issue_link();
    pure callback open_system_folder();

    about_dialog := AboutDialog {
        width: popup_width;
        height: popup_height;
        x: popup_x;
        y: popup_y;
    }

    about_slint := PopupWindow {
        width: popup_width;
        height: popup_height;
        x: popup_x;
        y: popup_y;

        Rectangle {
            background: Palette.background;

            AboutSlint { }
        }
    }

    logs := LogsDialog {
        width: popup_width;
        height: popup_height;
        x: popup_x;
        y: popup_y;
    }

    HorizontalBox {
        alignment: start;

        Rectangle {
            background: Palette.background;

            VerticalLayout {
                alignment: start;
                spacing: 0;

                MenuItem {
                    title: "File";

                    Button {
                        text: "Open System Folder";
                        clicked => {
                            open_system_folder();
                        }
                    }

                    Button {
                        text: "Quit";
                        clicked => {
                            quit()
                        }
                    }
                }

                MenuItem {
                    title: "View";

                    Button {
                        text: "Logs";
                        clicked => {
                            logs.show();
                        }
                    }
                }

                MenuItem {
                    title: "Help";

                    Button {
                        text: "Report an Issue";
                        clicked => {
                            Globals.open_url("https://github.com/obhq/obliteration/issues/new");
                        }
                    }

                    Button {
                        text: "About Slint";
                        clicked => {
                            about_slint.show();
                        }
                    }

                    Button {
                        text: "About Obliteration";
                        clicked => {
                            about_dialog.show();
                        }
                    }
                }
            }
        }
    }
}
