import { Button, StandardButton, AboutSlint, HorizontalBox, Palette } from "std-widgets.slint";
import { GlobalCallbacks } from "../globals.slint";

component MenuItem inherits Rectangle {
    background: Palette.background;

    in property <string> title;

    Button {
        text: title;
        clicked => {
            submenu.show();
        }
    }

    submenu := PopupWindow {
        x: parent.x + parent.width;

        VerticalLayout {
            spacing: 0;

            @children
        }
    }
}

export component Menu {
    in property <length> popup_width;
    in property <length> popup_height;
    in property <length> popup_x;
    in property <length> popup_y;

    pure callback quit();
    pure callback open_new_issue_link();
    pure callback open_system_folder();

    about_dialog := PopupWindow {
        width: popup_width;
        height: popup_height;
        x: popup_x;
        y: popup_y;

        Rectangle {
            background: Palette.background;

            Dialog {
                Text {
                    text: "Obliteration is a free and open-source software for playing your PlayStation 4 titles on PC.";
                }

                StandardButton {
                    kind: ok;
                }
            }
        }
    }

    about_slint := PopupWindow {
        width: popup_width;
        height: popup_height;
        x: popup_x;
        y: popup_y;

        Rectangle {
            background: Palette.background;

            AboutSlint { }
        }
    }

    logs := PopupWindow {
        width: popup_width;
        height: popup_height;
        x: popup_x;
        y: popup_y;

        Rectangle {
            background: Palette.background;

            Text {
                text: "Obliteration is a free and open-source software for playing your PlayStation 4 titles on PC.";
            }
        }
    }

    HorizontalBox {
        alignment: start;

        Rectangle {
            background: Palette.background;

            VerticalLayout {
                alignment: start;
                spacing: 0;

                MenuItem {
                    title: "File";

                    Button {
                        text: "Open System Folder";
                        clicked => {
                            open_system_folder();
                        }
                    }

                    Button {
                        text: "Quit";
                        clicked => {
                            quit()
                        }
                    }
                }

                MenuItem {
                    title: "View";

                    Button {
                        text: "Logs";
                        clicked => {
                            logs.show();
                        }
                    }
                }

                MenuItem {
                    title: "Help";

                    Button {
                        text: "Report an Issue";
                        clicked => {
                            GlobalCallbacks.open_url("https://github.com/obhq/obliteration/issues/new");
                        }
                    }

                    Button {
                        text: "About Slint";
                        clicked => {
                            about_slint.show();
                        }
                    }

                    Button {
                        text: "About Obliteration";
                        clicked => {
                            about_dialog.show();
                        }
                    }
                }
            }
        }
    }
}
