
import { TabWidget, Button, HorizontalBox } from "std-widgets.slint";
import { DisplayTab } from "tabs/display.slint";
import { CpuTab } from "tabs/cpu.slint";
import { Menu } from "menu.slint";

export component Tabs {
    in property <[string]> devices: [];

    property <int> tab: 1;

    VerticalLayout {
        HorizontalBox {
            Button {
                icon: @image-url("menu.svg");
                primary: root.tab == 0;
                clicked => { root.tab = 0 }
            }

            Button {
                text: "Display";
                icon: @image-url("../../resources/monitor.svg");
                horizontal-stretch: 1;
                primary: root.tab == 1;
                clicked => { root.tab = 1 }
            }

            Button {
                text: "CPU";
                icon: @image-url("../../resources/cpu-64-bit.svg");
                horizontal-stretch: 1;
                primary: root.tab == 2;
                clicked => { root.tab = 2 }
            }
        }

        if root.tab == 0: Menu {
            vertical-stretch: 1;
        }

        if root.tab == 1: DisplayTab {
            devices: devices;
            vertical-stretch: 1;
        }

        if root.tab == 2: CpuTab {
            vertical-stretch: 1;
        }
    }
}
