[package]
name = "pfs"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8"
flate2 = "1.0"
generic-array = "0.14"
hmac = "0.12"
sha2 = "0.10"
thiserror = "1.0"
util = { path = "../util" }
xts-mode = "0.5"
