[package]
name = "gmtx"
version = "0.1.0"
edition = "2021"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = ["Win32_System_Threading"] }

[target.'cfg(target_os = "macos")'.dependencies]
ulock-sys = "0.1.0"
