[package]
name = "gmtx"
version = "0.1.0"
edition = "2021"

[dependencies]
tls = { path = "../tls" }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = ["Win32_System_Threading"] }
