version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  labels: []
- package-ecosystem: cargo
  directory: "/src"
  schedule:
    interval: daily
  labels: []
