[workspace]
resolver = "2"
members = [
    "gui",
    "kernel",
    "src/fs",
    "src/gmtx",
    "src/kernel",
    "src/llt",
    "src/macros",
    "src/obconf",
    "src/param",
    "src/pfs",
    "src/pkg",
    "src/tls"
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = "full"
lto = true
