[workspace]
resolver = "2"
members = [
    "arch/aarch64",
    "arch/x86-64",
    "gui",
    "kernel",
    "macros",
    "src/fs",
    "src/llt",
    "src/obconf",
    "src/tls",
]
default-members = ["gui"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
