site_name: Obliteration Developer
nav:
  - 'index.md'
  - 'Reference':
    - 'Kernel': 'https://dev.obliteration.net/crates/obkrnl'
repo_url: https://github.com/obhq/obliteration
repo_name: obhq/obliteration
edit_uri: edit/main/docs/
markdown_extensions:
  - mdx_truly_sane_lists
theme:
  name: readthedocs
