import { Button, ComboBox, HorizontalBox } from "std-widgets.slint";
import { Globals, GlobalModels } from "../globals.slint";

export component Actions {
    pure callback start_game();

    HorizontalBox {
        padding: 0;

        ComboBox {
            model: GlobalModels.profiles;
            horizontal-stretch: 1;
        }

        Button {
            text: "Start";
            icon: @image-url("../../resources/play.svg");
            clicked => {
                start_game();
            }
        }

        Button {
            text: "Save";
            icon: @image-url("../../resources/content-save.svg");
        }
    }
}
