import { Button, ComboBox, HorizontalBox } from "std-widgets.slint";

export component Actions {
    in property <[string]> profiles;
    in-out property <int> selected-profile;

    callback profile-selected();
    pure callback save();
    pure callback start();

    HorizontalBox {
        padding: 0;

        ComboBox {
            model: root.profiles;
            current-index <=> selected-profile;
            horizontal-stretch: 1;
            selected => {
                profile-selected();
            }
        }

        Button {
            text: "Save";
            icon: @image-url("actions/save.svg");
            colorize-icon: true;
            clicked => {
                save();
            }
        }

        Button {
            text: "Start";
            icon: @image-url("actions/start.svg");
            colorize-icon: true;
            clicked => {
                start();
            }
        }
    }
}
