import { Button, Slider, LineEdit, HorizontalBox, VerticalBox } from "std-widgets.slint";

export component CpuTab {
    property <string> debug-address: "127.0.0.1:1234";

    pure callback start-debug(string);

    HorizontalBox {
        padding: 0;

        VerticalBox {
            alignment: start;

            property <float> cpus: 8;

            Text {
                text: "Count";
            }

            HorizontalBox {
                Slider {
                    value <=> cpus;
                    minimum: 1;
                    maximum: 16;
                    changed => {
                        cpus = Math.round(cpus);
                    }
                }

                Text {
                    vertical-alignment: center;
                    text: cpus;
                }
            }

            Text {
                text: "Changing this value to other than 8 may crash the game.";
            }
        }

        VerticalBox {
            alignment: start;

            Text {
                text: "Debug";
            }

            HorizontalBox {
                Text {
                    text: "Listen address";
                    vertical-alignment: center;
                }

                LineEdit {
                    text <=> debug-address;
                }

                Button {
                    text: "Start";
                    clicked => {
                        start-debug(debug-address);
                    }
                }
            }

            Text {
                text: "Specify a TCP address to listen for a debugger. The kernel will wait for a debugger to connect before start.";
            }
        }
    }
}
