import { ComboBox, HorizontalBox, VerticalBox, GroupBox } from "std-widgets.slint";

export component DisplayTab {
    in property <[string]> devices;
    in property <[string]> resolutions;
    in-out property <int> selected-resolution;

    VerticalBox {
        padding: 0;
        alignment: start;

        HorizontalBox {
            padding: 0;

            GroupBox {
                title: "Device";
                width: 50%;
                ComboBox {
                    model: devices;
                }
            }

            GroupBox {
                title: "Resolution";
                ComboBox {
                    model: resolutions;
                    current-index <=> selected-resolution;
                }
            }
        }
    }
}
