import { VerticalBox, StandardTableView, Button } from "std-widgets.slint";

export component EnvironmentTab {
    in property <[[StandardListViewItem]]> list;

    callback new();

    VerticalBox {
        StandardTableView {
            columns: [{ title: "Name" }, { title: "Value" }];
            rows: root.list;
        }

        Button {
            text: "New";
            clicked => {
                new();
            }
        }
    }
}
