import { Button, StandardButton, AboutSlint, HorizontalBox, Palette, VerticalBox } from "std-widgets.slint";

enum Page {
    help,
    about
}

component SideBarItem {
    in property <bool> selected;
    in-out property <string> text <=> label.text;

    callback clicked <=> touch.clicked;

    min-height: l.preferred-height;

    states [
        pressed when touch.pressed: {
            state.opacity: 0.8;
        }
        hover when touch.has-hover: {
            state.opacity: 0.6;
        }
        selected when root.selected: {
            state.opacity: 1;
        }
    ]

    state := Rectangle {
        opacity: 0;
        background: Palette.background;

        animate opacity { duration: 150ms; }
    }

    l := HorizontalBox {
        label := Text { }
    }

    touch := TouchArea {
        width: 100%;
        height: 100%;
    }
}

component SideBar {
    out property <Page> current-page;

    width: 180px;

    Rectangle {
        background: Palette.alternate-background;
    }

    VerticalLayout {
        alignment: start;

        SideBarItem {
            text: "Help";
            selected: root.current-page == Page.help;
            clicked => {
                root.current-page = Page.help;
            }
        }

        SideBarItem {
            text: "About";
            selected: root.current-page == Page.about;
            clicked => {
                root.current-page = Page.about;
            }
        }
    }
}

component Help {
    pure callback report-issue();

    Button {
        text: "Report an Issue";
        clicked => {
            report-issue();
        }
    }
}

component About {
    VerticalLayout {
        Text {
            text: "Obliteration is a free and open-source software to run PlayStation 4 system software on PC.";
            horizontal-alignment: center;
        }

        AboutSlint { }
    }
}

export component Menu {
    pure callback report-issue();

    HorizontalBox {
        padding: 0;

        nav := SideBar { }

        if nav.current-page == Page.help: Help {
            report-issue => {
                report-issue();
            }
        }

        if nav.current-page == Page.about: About { }
    }
}
