import { Button, StandardButton, AboutSlint, HorizontalBox, Palette, VerticalBox } from "std-widgets.slint";
import { Globals } from "../globals.slint";

enum Page {
    Help,
    About
}

component SideBarItem {
    in property <bool> selected;
    in-out property <string> text <=> label.text;

    callback clicked <=> touch.clicked;

    min-height: l.preferred-height;

    states [
        pressed when touch.pressed: {
            state.opacity: 0.8;
        }
        hover when touch.has-hover: {
            state.opacity: 0.6;
        }
        selected when root.selected: {
            state.opacity: 1;
        }
    ]

    state := Rectangle {
        opacity: 0;
        background: Palette.background;

        animate opacity { duration: 150ms; }
    }

    l := HorizontalBox {
        label := Text { }
    }

    touch := TouchArea {
        width: 100%;
        height: 100%;
    }
}

component SideBar {
    out property <Page> current-page;

    width: 180px;

    Rectangle {
        background: Palette.background.darker(0.2);
    }

    VerticalLayout {
        alignment: start;

        SideBarItem {
            text: "Help";
            selected: root.current-page == Page.Help;
            clicked => {
                root.current-page = Page.Help;
            }
        }

        SideBarItem {
            text: "About";
            selected: root.current-page == Page.About;
            clicked => {
                root.current-page = Page.About;
            }
        }
    }
}

component Help {
    Button {
        text: "Report an Issue";
        clicked => {
            Globals.open_url("https://github.com/obhq/obliteration/issues/new");
        }
    }
}

component About {
    VerticalLayout {
        Text {
            text: "Obliteration is a free and open-source software for playing your PlayStation 4 titles on PC.";
            horizontal-alignment: center;
        }

        AboutSlint { }
    }
}

export component Menu {
    in property <length> popup_width;
    in property <length> popup_height;
    in property <length> popup_x;
    in property <length> popup_y;

    HorizontalBox {
        padding: 0;

        nav := SideBar { }

        if nav.current-page == Page.Help: Help { }
        if nav.current-page == Page.About: About { }
    }
}
