import { Button, HorizontalBox, VerticalBox } from "std-widgets.slint";
import { DisplayTab } from "display.slint";
import { CpuTab } from "cpu.slint";
import { Menu } from "menu.slint";

enum Tab {
    menu,
    display,
    cpu
}

export component Tabs {
    in property <[string]> devices;

    pure callback report-issue();
    pure callback start-debug(string);

    private property <Tab> tab: Tab.display;

    VerticalBox {
        padding: 0;

        HorizontalBox {
            padding: 0;

            Button {
                icon: @image-url("menu.svg");
                colorize-icon: true;
                primary: root.tab == Tab.menu;
                clicked => {
                    root.tab = Tab.menu
                }
            }

            Button {
                text: "Display";
                icon: @image-url("monitor.svg");
                colorize-icon: true;
                primary: root.tab == Tab.display;
                horizontal-stretch: 1;
                clicked => {
                    root.tab = Tab.display
                }
            }

            Button {
                text: "CPU";
                icon: @image-url("cpu-64-bit.svg");
                colorize-icon: true;
                primary: root.tab == Tab.cpu;
                horizontal-stretch: 1;
                clicked => {
                    root.tab = Tab.cpu
                }
            }
        }

        if root.tab == Tab.menu: Menu {
            vertical-stretch: 1;

            report-issue => {
                report-issue();
            }
        }

        if root.tab == Tab.display: DisplayTab {
            devices: root.devices;
            vertical-stretch: 1;
        }

        if root.tab == Tab.cpu: CpuTab {
            vertical-stretch: 1;
            start-debug(addr) => {
                start-debug(addr);
            }
        }
    }
}
