import { ComboBox, HorizontalBox, VerticalBox } from "std-widgets.slint";

export component DisplayTab {
    in property <[string]> devices: [];

    HorizontalBox {
        padding: 0;

        VerticalBox {
            alignment: start;

            Text {
                text: "Device";
            }

            ComboBox {
                model: devices;
            }
        }

        VerticalBox {
            alignment: start;

            Text {
                text: "Resolution";
            }

            ComboBox {
                model: ["1280 × 720", "1920 × 1080", "3840 × 2160"];
                current-value: "1920 × 1080";
            }
        }
    }
}
