import { ComboBox, HorizontalBox, VerticalBox } from "std-widgets.slint";
import { GlobalModels } from "../../globals.slint";

export component DisplayTab {
    HorizontalBox {
        VerticalBox {
            alignment: start;

            Text {
                text: "Device";
            }

            ComboBox {
                model: GlobalModels.devices;
            }
        }

        VerticalBox {
            alignment: start;

            Text {
                text: "Resolution";
            }

            ComboBox {
                model: ["1280 × 720", "1920 × 1080", "3840 × 2160"];
                current-value: "1920 × 1080";
            }
        }
    }
}
