use super::{RegisterAlias, RegisterCategory, RegisterFormat, RegisterType};
use num_enum::{IntoPrimitive, TryFromPrimitive};
use std::fmt::{Display, Formatter};
use std::mem::offset_of;

/// Register identifier for AArch64.
///
/// Note that we cannot have a gap between the variant since the debugger will treat absent number
/// as the end of register list.
#[repr(usize)]
#[derive(Clone, Copy, IntoPrimitive, TryFromPrimitive)]
pub(super) enum Register {
    X0,
    X1,
    X2,
    X3,
    X4,
    X5,
    X6,
    X7,
    X8,
    X9,
    X10,
    X11,
    X12,
    X13,
    X14,
    X15,
    X16,
    X17,
    X18,
    X19,
    X20,
    X21,
    X22,
    X23,
    X24,
    X25,
    X26,
    X27,
    X28,
    X29,
    X30,
    Sp,
    Pc,
}

impl Register {
    pub fn ty(self) -> RegisterType {
        match self {
            Self::X0 => RegisterType::Unsigned,
            Self::X1 => RegisterType::Unsigned,
            Self::X2 => RegisterType::Unsigned,
            Self::X3 => RegisterType::Unsigned,
            Self::X4 => RegisterType::Unsigned,
            Self::X5 => RegisterType::Unsigned,
            Self::X6 => RegisterType::Unsigned,
            Self::X7 => RegisterType::Unsigned,
            Self::X8 => RegisterType::Unsigned,
            Self::X9 => RegisterType::Unsigned,
            Self::X10 => RegisterType::Unsigned,
            Self::X11 => RegisterType::Unsigned,
            Self::X12 => RegisterType::Unsigned,
            Self::X13 => RegisterType::Unsigned,
            Self::X14 => RegisterType::Unsigned,
            Self::X15 => RegisterType::Unsigned,
            Self::X16 => RegisterType::Unsigned,
            Self::X17 => RegisterType::Unsigned,
            Self::X18 => RegisterType::Unsigned,
            Self::X19 => RegisterType::Unsigned,
            Self::X20 => RegisterType::Unsigned,
            Self::X21 => RegisterType::Unsigned,
            Self::X22 => RegisterType::Unsigned,
            Self::X23 => RegisterType::Unsigned,
            Self::X24 => RegisterType::Unsigned,
            Self::X25 => RegisterType::Unsigned,
            Self::X26 => RegisterType::Unsigned,
            Self::X27 => RegisterType::Unsigned,
            Self::X28 => RegisterType::Unsigned,
            Self::X29 => RegisterType::Unsigned,
            Self::X30 => RegisterType::Unsigned,
            Self::Sp => RegisterType::Unsigned,
            Self::Pc => RegisterType::Unsigned,
        }
    }

    pub fn category(self) -> RegisterCategory {
        match self {
            Self::X0 => RegisterCategory::General,
            Self::X1 => RegisterCategory::General,
            Self::X2 => RegisterCategory::General,
            Self::X3 => RegisterCategory::General,
            Self::X4 => RegisterCategory::General,
            Self::X5 => RegisterCategory::General,
            Self::X6 => RegisterCategory::General,
            Self::X7 => RegisterCategory::General,
            Self::X8 => RegisterCategory::General,
            Self::X9 => RegisterCategory::General,
            Self::X10 => RegisterCategory::General,
            Self::X11 => RegisterCategory::General,
            Self::X12 => RegisterCategory::General,
            Self::X13 => RegisterCategory::General,
            Self::X14 => RegisterCategory::General,
            Self::X15 => RegisterCategory::General,
            Self::X16 => RegisterCategory::General,
            Self::X17 => RegisterCategory::General,
            Self::X18 => RegisterCategory::General,
            Self::X19 => RegisterCategory::General,
            Self::X20 => RegisterCategory::General,
            Self::X21 => RegisterCategory::General,
            Self::X22 => RegisterCategory::General,
            Self::X23 => RegisterCategory::General,
            Self::X24 => RegisterCategory::General,
            Self::X25 => RegisterCategory::General,
            Self::X26 => RegisterCategory::General,
            Self::X27 => RegisterCategory::General,
            Self::X28 => RegisterCategory::General,
            Self::X29 => RegisterCategory::General,
            Self::X30 => RegisterCategory::General,
            Self::Sp => RegisterCategory::General,
            Self::Pc => RegisterCategory::General,
        }
    }

    pub fn alias(self) -> Option<RegisterAlias> {
        match self {
            Self::Sp => Some(RegisterAlias::StackPointer),
            Self::Pc => Some(RegisterAlias::ProgramCounter),
            _ => None,
        }
    }

    /// Returns size of the register, in bits.
    pub fn size(self) -> u8 {
        match self {
            Self::X0 => 64,
            Self::X1 => 64,
            Self::X2 => 64,
            Self::X3 => 64,
            Self::X4 => 64,
            Self::X5 => 64,
            Self::X6 => 64,
            Self::X7 => 64,
            Self::X8 => 64,
            Self::X9 => 64,
            Self::X10 => 64,
            Self::X11 => 64,
            Self::X12 => 64,
            Self::X13 => 64,
            Self::X14 => 64,
            Self::X15 => 64,
            Self::X16 => 64,
            Self::X17 => 64,
            Self::X18 => 64,
            Self::X19 => 64,
            Self::X20 => 64,
            Self::X21 => 64,
            Self::X22 => 64,
            Self::X23 => 64,
            Self::X24 => 64,
            Self::X25 => 64,
            Self::X26 => 64,
            Self::X27 => 64,
            Self::X28 => 64,
            Self::X29 => 64,
            Self::X30 => 64,
            Self::Sp => 64,
            Self::Pc => 64,
        }
    }

    /// Returns offset of the register within `g` and `G` response.
    pub fn offset(self) -> usize {
        match self {
            Self::X0 => offset_of!(Registers, x0),
            Self::X1 => offset_of!(Registers, x1),
            Self::X2 => offset_of!(Registers, x2),
            Self::X3 => offset_of!(Registers, x3),
            Self::X4 => offset_of!(Registers, x4),
            Self::X5 => offset_of!(Registers, x5),
            Self::X6 => offset_of!(Registers, x6),
            Self::X7 => offset_of!(Registers, x7),
            Self::X8 => offset_of!(Registers, x8),
            Self::X9 => offset_of!(Registers, x9),
            Self::X10 => offset_of!(Registers, x10),
            Self::X11 => offset_of!(Registers, x11),
            Self::X12 => offset_of!(Registers, x12),
            Self::X13 => offset_of!(Registers, x13),
            Self::X14 => offset_of!(Registers, x14),
            Self::X15 => offset_of!(Registers, x15),
            Self::X16 => offset_of!(Registers, x16),
            Self::X17 => offset_of!(Registers, x17),
            Self::X18 => offset_of!(Registers, x18),
            Self::X19 => offset_of!(Registers, x19),
            Self::X20 => offset_of!(Registers, x20),
            Self::X21 => offset_of!(Registers, x21),
            Self::X22 => offset_of!(Registers, x22),
            Self::X23 => offset_of!(Registers, x23),
            Self::X24 => offset_of!(Registers, x24),
            Self::X25 => offset_of!(Registers, x25),
            Self::X26 => offset_of!(Registers, x26),
            Self::X27 => offset_of!(Registers, x27),
            Self::X28 => offset_of!(Registers, x28),
            Self::X29 => offset_of!(Registers, x29),
            Self::X30 => offset_of!(Registers, x30),
            Self::Sp => offset_of!(Registers, sp),
            Self::Pc => offset_of!(Registers, pc),
        }
    }

    pub fn format(self) -> RegisterFormat {
        match self {
            Self::X0 => RegisterFormat::Hex,
            Self::X1 => RegisterFormat::Hex,
            Self::X2 => RegisterFormat::Hex,
            Self::X3 => RegisterFormat::Hex,
            Self::X4 => RegisterFormat::Hex,
            Self::X5 => RegisterFormat::Hex,
            Self::X6 => RegisterFormat::Hex,
            Self::X7 => RegisterFormat::Hex,
            Self::X8 => RegisterFormat::Hex,
            Self::X9 => RegisterFormat::Hex,
            Self::X10 => RegisterFormat::Hex,
            Self::X11 => RegisterFormat::Hex,
            Self::X12 => RegisterFormat::Hex,
            Self::X13 => RegisterFormat::Hex,
            Self::X14 => RegisterFormat::Hex,
            Self::X15 => RegisterFormat::Hex,
            Self::X16 => RegisterFormat::Hex,
            Self::X17 => RegisterFormat::Hex,
            Self::X18 => RegisterFormat::Hex,
            Self::X19 => RegisterFormat::Hex,
            Self::X20 => RegisterFormat::Hex,
            Self::X21 => RegisterFormat::Hex,
            Self::X22 => RegisterFormat::Hex,
            Self::X23 => RegisterFormat::Hex,
            Self::X24 => RegisterFormat::Hex,
            Self::X25 => RegisterFormat::Hex,
            Self::X26 => RegisterFormat::Hex,
            Self::X27 => RegisterFormat::Hex,
            Self::X28 => RegisterFormat::Hex,
            Self::X29 => RegisterFormat::Hex,
            Self::X30 => RegisterFormat::Hex,
            Self::Sp => RegisterFormat::Hex,
            Self::Pc => RegisterFormat::Hex,
        }
    }

    /// Returns DWARF register number according to
    /// https://github.com/ARM-software/abi-aa/blob/main/aadwarf64/aadwarf64.rst.
    pub fn dwarf_number(self) -> usize {
        match self {
            Self::X0 => 0,
            Self::X1 => 1,
            Self::X2 => 2,
            Self::X3 => 3,
            Self::X4 => 4,
            Self::X5 => 5,
            Self::X6 => 6,
            Self::X7 => 7,
            Self::X8 => 8,
            Self::X9 => 9,
            Self::X10 => 10,
            Self::X11 => 11,
            Self::X12 => 12,
            Self::X13 => 13,
            Self::X14 => 14,
            Self::X15 => 15,
            Self::X16 => 16,
            Self::X17 => 17,
            Self::X18 => 18,
            Self::X19 => 19,
            Self::X20 => 20,
            Self::X21 => 21,
            Self::X22 => 22,
            Self::X23 => 23,
            Self::X24 => 24,
            Self::X25 => 25,
            Self::X26 => 26,
            Self::X27 => 27,
            Self::X28 => 28,
            Self::X29 => 29,
            Self::X30 => 30,
            Self::Sp => 31,
            Self::Pc => 32,
        }
    }
}

impl Display for Register {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::X0 => "x0",
            Self::X1 => "x1",
            Self::X2 => "x2",
            Self::X3 => "x3",
            Self::X4 => "x4",
            Self::X5 => "x5",
            Self::X6 => "x6",
            Self::X7 => "x7",
            Self::X8 => "x8",
            Self::X9 => "x9",
            Self::X10 => "x10",
            Self::X11 => "x11",
            Self::X12 => "x12",
            Self::X13 => "x13",
            Self::X14 => "x14",
            Self::X15 => "x15",
            Self::X16 => "x16",
            Self::X17 => "x17",
            Self::X18 => "x18",
            Self::X19 => "x19",
            Self::X20 => "x20",
            Self::X21 => "x21",
            Self::X22 => "x22",
            Self::X23 => "x23",
            Self::X24 => "x24",
            Self::X25 => "x25",
            Self::X26 => "x26",
            Self::X27 => "x27",
            Self::X28 => "x28",
            Self::X29 => "x29",
            Self::X30 => "x30",
            Self::Sp => "sp",
            Self::Pc => "pc",
        })
    }
}

/// Raw content for `g` and `G` response.
#[repr(C, packed)]
pub struct Registers {
    pub x0: usize,
    pub x1: usize,
    pub x2: usize,
    pub x3: usize,
    pub x4: usize,
    pub x5: usize,
    pub x6: usize,
    pub x7: usize,
    pub x8: usize,
    pub x9: usize,
    pub x10: usize,
    pub x11: usize,
    pub x12: usize,
    pub x13: usize,
    pub x14: usize,
    pub x15: usize,
    pub x16: usize,
    pub x17: usize,
    pub x18: usize,
    pub x19: usize,
    pub x20: usize,
    pub x21: usize,
    pub x22: usize,
    pub x23: usize,
    pub x24: usize,
    pub x25: usize,
    pub x26: usize,
    pub x27: usize,
    pub x28: usize,
    pub x29: usize,
    pub x30: usize,
    pub sp: usize,
    pub pc: usize,
}
