[package]
name = "pup"
version = "0.1.0"
edition = "2021"

[dependencies]
error = { path = "../error" }
exfat = { path = "../exfat" }
flate2 = "1.0"
memmap2 = "0.5"
thiserror = "1.0"
util = { path = "../util" }
