import { CheckBox, VerticalBox, GroupBox } from "std-widgets.slint";

export component GraphicsTab {
    in property <string> debug-layer-name;
    in-out property <bool> debug-layer-checked;

    VerticalBox {
        padding-top: 0;
        padding-bottom: 0;

        GroupBox {
            title: "Debug";

            VerticalLayout {
                alignment: start;

                CheckBox {
                    text: "Enable \{debug-layer-name} (restart required)";
                    checked <=> root.debug-layer-checked;
                }
            }
        }
    }
}
