[package]
name = "obkrnl"
version = "0.1.0"
edition = "2021"

[dependencies]
anstyle = { version = "1.0.8", default-features = false }
macros = { path = "../macros" }
obconf = { path = "../obconf" }
obvirt = { path = "../obvirt" }
