import { StandardButton, GroupBox, LineEdit } from "std-widgets.slint";

export component EditEnvironment inherits Dialog {
    in property <string> dialog-title;
    in-out property <string> name;
    in-out property <string> value;

    title: root.dialog-title;
    min-width: 400px;

    VerticalLayout {
        alignment: start;

        GroupBox {
            title: "Name";

            LineEdit {
                text <=> root.name;
            }
        }

        GroupBox {
            title: "Value";

            LineEdit {
                text <=> root.value;
            }
        }
    }

    StandardButton {
        kind: ok;
    }

    StandardButton {
        kind: cancel;
    }
}
