import { Tabs } from "main/tabs.slint";
import { Actions } from "main/actions.slint";
import { Globals } from "globals.slint";
import { VerticalBox } from "std-widgets.slint";

export { ErrorWindow } from "error.slint";
export { SetupWizard } from "setup.slint";
export { Globals }

export component MainWindow inherits Window {
    title: "Obliteration";
    icon: @image-url("icon.png");
    min-width: 1000px;
    min-height: 500px;

    in property <[string]> devices;
    in property <[string]> profiles;

    pure callback start-vmm();

    VerticalBox {
        Tabs {
            devices: devices;
        }

        Actions {
            profiles: profiles;
            start => {
                start-vmm();
            }
        }
    }
}
