import { VerticalBox, HorizontalBox, Button, ComboBox } from "std-widgets.slint";
import { TabBar, TabContainer } from "@root/widgets/tab.slint";
import { CpuTab } from "main/cpu.slint";
import { DisplayTab } from "main/display.slint";
import { IdpsTab } from "main/idps.slint";

export component MainWindow inherits Window {
    in property <[string]> devices;
    in-out property <int> selected-device;
    in property <[string]> resolutions;
    in-out property <int> selected-resolution;
    in property <[string]> cpu-models;
    in-out property <int> selected-cpu;
    in-out property <int> cpu-count;
    in-out property <string> debug-address;
    in property <[string]> idps-products;
    in property <[string]> profiles;
    in-out property <int> selected-profile;

    callback settings();
    callback new-profile();
    callback report-issue();
    pure callback about();
    callback profile-selected();
    pure callback save-profile();
    pure callback start-vmm();
    pure callback start-debug();

    title: "Obliteration";
    icon: @image-url("@root/assets/icon.png");
    min-width: 1000px;
    min-height: 500px;

    // Menu.
    MenuBar {
        // Edit
        Menu {
            title: "Edit";

            MenuItem {
                title: "Settings";
                activated => {
                    settings();
                }
            }
        }

        // Profile
        Menu {
            title: "Profile";

            MenuItem {
                title: "New Profile...";
                activated => {
                    new-profile();
                }
            }
        }

        // Help.
        Menu {
            title: "Help";

            MenuItem {
                title: "Report Issue";
                activated => {
                    report-issue();
                }
            }

            MenuItem {
                title: "About";
                activated => {
                    about();
                }
            }
        }
    }

    // Content.
    VerticalBox {
        // Tab.
        TabContainer {
            vertical-stretch: 1;

            tab := TabBar {
                tabs: [
                    { text: "Display", icon: @image-url("@root/assets/monitor.svg"), colorize-icon: true },
                    { text: "CPU", icon: @image-url("@root/assets/cpu-64-bit.svg"), colorize-icon: true },
                    {
                        text: "IDPS",
                        icon: @image-url("@root/assets/sony-playstation.svg"),
                        colorize-icon: true
                    }
                ];
            }

            if tab.current-page == 0: DisplayTab {
                devices: root.devices;
                selected-device <=> root.selected-device;
                resolutions: root.resolutions;
                selected-resolution <=> root.selected-resolution;
            }

            if tab.current-page == 1: CpuTab {
                cpu-models: root.cpu-models;
                selected-cpu <=> root.selected-cpu;
                cpu-count <=> root.cpu-count;
                debug-address <=> root.debug-address;
                start-debug => {
                    start-debug();
                }
            }

            if tab.current-page == 2: IdpsTab {
                products: root.idps-products;
            }
        }

        // Profile + actions.
        HorizontalBox {
            padding: 0;

            ComboBox {
                model: profiles;
                current-index <=> selected-profile;
                horizontal-stretch: 1;
                selected => {
                    profile-selected();
                }
            }

            Button {
                text: "Save";
                icon: @image-url("main/save.svg");
                colorize-icon: true;
                clicked => {
                    save-profile();
                }
            }

            Button {
                text: "Start";
                icon: @image-url("main/start.svg");
                colorize-icon: true;
                clicked => {
                    start-vmm();
                }
            }
        }
    }
}
