import { Tabs } from "main/tabs.slint";
import { Actions } from "main/actions.slint";
import { VerticalBox } from "std-widgets.slint";

export { WaitForDebugger } from "debug.slint";
export { ErrorWindow } from "error.slint";
export { InstallFirmware, SetupWizard } from "setup.slint";

export component MainWindow inherits Window {
    in property <[string]> devices;
    in property <[string]> resolutions;
    in-out property <int> selected-resolution;
    in property <[string]> profiles;
    in-out property <int> selected-profile <=> actions.selected-profile;

    callback profile-selected <=> actions.profile-selected;
    pure callback save-profile <=> actions.save;
    pure callback report-issue();
    pure callback start-vmm <=> actions.start;
    pure callback start-debug <=> tabs.start-debug;

    title: "Obliteration";
    icon: @image-url("icon.png");
    min-width: 1000px;
    min-height: 500px;

    VerticalBox {
        tabs := Tabs {
            devices: devices;
            resolutions: resolutions;
            selected-resolution <=> selected-resolution;
            vertical-stretch: 1;
            report-issue => {
                report-issue();
            }
        }

        actions := Actions {
            profiles: profiles;
        }
    }
}
