import { StandardButton, GroupBox, LineEdit } from "std-widgets.slint";

export component NewProfile inherits Dialog {
    out property <string> name;

    title: "New Profile";
    min-width: 400px;

    VerticalLayout {
        alignment: start;

        GroupBox {
            title: "Name";

            LineEdit {
                text <=> root.name;
            }
        }
    }

    StandardButton {
        kind: ok;
    }

    StandardButton {
        kind: cancel;
    }
}
