import { Intro } from "setup/intro.slint";
import { Firmware, InstallFirmware } from "setup/firmware.slint";
import { Conclusion } from "setup/conclusion.slint";
import { NavBar } from "setup/nav.slint";
import { Palette } from "std-widgets.slint";

// https://github.com/slint-ui/slint/issues/6880
enum WizardPage {
    Intro,
    Firmware,
    Conclusion
}

export component SetupWizard inherits Window {
    title: "Setup Obliteration";
    icon: @image-url("icon.png");
    width: 500px; // PopupWindow does not resize with the window somehow.
    height: 400px; // Same here.

    in-out property <string> firmware-dump;

    pure callback cancel <=> nav.cancel;
    pure callback browse-firmware();
    pure callback finish();

    private property <WizardPage> page: WizardPage.Intro;

    states [
        finished when page == WizardPage.Conclusion: {
            nav.next-text: "Finish";
        }
    ]

    VerticalLayout {
        if page == WizardPage.Intro: Intro {
            vertical-stretch: 1;
        }

        if page == WizardPage.Firmware: Firmware {
            firmware-dump: root.firmware-dump;
            vertical-stretch: 1;

            browse => {
                browse-firmware();
            }
        }

        if page == WizardPage.Conclusion: Conclusion {
            vertical-stretch: 1;
        }

        nav := NavBar {
            back-text: "＜ Back";
            back-enabled: root.page != WizardPage.Intro && root.page != WizardPage.Conclusion;
            next-text: "Next ＞";
            back-clicked => {
                if root.page == WizardPage.Firmware {
                    root.page = WizardPage.Intro;
                }
            }
            next-clicked => {
                if root.page == WizardPage.Intro {
                    root.page = WizardPage.Firmware;
                } else if root.page == WizardPage.Firmware {
                    install-firmware.show();
                } else if root.page == WizardPage.Conclusion {
                    finish();
                }
            }
        }
    }

    install-firmware := InstallFirmware {
        x: 10px;
        y: 150px;
        width: parent.width - 20px;
        height: parent.height - 300px;
    }
}
