import { Intro } from "setup/intro.slint";
import { Firmware, InstallFirmware } from "setup/firmware.slint";
import { Conclusion } from "setup/conclusion.slint";
import { NavBar } from "setup/nav.slint";
import { Palette } from "std-widgets.slint";
import { ErrorPopup } from "error.slint";

// https://github.com/slint-ui/slint/issues/6880
enum WizardPage {
    Intro,
    Firmware,
    Conclusion
}

export enum FirmwareInstaller {
    Stopped,
    Running
}

export component SetupWizard inherits Window {
    in-out property <string> firmware-dump;
    in-out property <FirmwareInstaller> firmware-installer;
    in property <string> firmware-status;
    in property <float> firmware-progress;
    in-out property <string> error-message;

    pure callback cancel <=> nav.cancel;
    pure callback browse-firmware();
    pure callback install-firmware();
    pure callback finish();

    title: "Setup Obliteration";
    icon: @image-url("icon.png");
    width: 500px; // PopupWindow does not resize with the window somehow.
    height: 400px; // Same here.

    private property <WizardPage> page: WizardPage.Intro;

    states [
        finished when page == WizardPage.Conclusion: {
            nav.next-text: "Finish";
        }
    ]

    VerticalLayout {
        if page == WizardPage.Intro: Intro {
            vertical-stretch: 1;
        }

        if page == WizardPage.Firmware: Firmware {
            firmware-dump: firmware-dump;
            vertical-stretch: 1;

            browse => {
                browse-firmware();
            }

            changed firmware-dump => {
                firmware-dump = self.firmware-dump;
            }
        }

        if page == WizardPage.Conclusion: Conclusion {
            vertical-stretch: 1;
        }

        nav := NavBar {
            back-text: "＜ Back";
            back-enabled: root.page != WizardPage.Intro && root.page != WizardPage.Conclusion;
            next-text: "Next ＞";
            back-clicked => {
                if root.page == WizardPage.Firmware {
                    root.page = WizardPage.Intro;
                }
            }
            next-clicked => {
                if root.page == WizardPage.Intro {
                    root.page = WizardPage.Firmware;
                } else if root.page == WizardPage.Firmware {
                    install-firmware();
                } else if root.page == WizardPage.Conclusion {
                    finish();
                }
            }
        }
    }

    firmware-popup := InstallFirmware {
        x: 10px;
        y: 150px;
        width: parent.width - 20px;
        height: parent.height - 300px;
        status: firmware-status;
        progress: firmware-progress;
    }

    error-popup := ErrorPopup {
        x: 10px;
        y: (parent.height / 2) - 50px;
        width: parent.width - 20px;
        message: error-message;
        close-clicked => {
            error-message = "";
        }
    }

    changed firmware-installer => {
        if firmware-installer == FirmwareInstaller.Running {
            firmware-popup.show();
        }
    }

    changed error-message => {
        if error-message == "" {
            error-popup.close();
        } else {
            error-popup.show();
        }
    }
}
