import { VerticalBox, HorizontalBox, LineEdit, Button, Palette, ProgressIndicator } from "std-widgets.slint";
import { Header } from "header.slint";

export component Firmware {
    in-out property <string> firmware-dump <=> input.text;

    pure callback browse();

    VerticalBox {
        Header {
            title: "Install Firmware";
        }

        Text {
            text: "Select a firmware dump that you got from Firmware Dumper.";
        }

        HorizontalBox {
            padding: 0;

            input := LineEdit {
                placeholder-text: "Path to a firmware dump";
            }

            Button {
                text: "...";
                clicked => {
                    browse();
                }
            }
        }

        Rectangle { }
    }
}

export component InstallFirmware inherits PopupWindow {
    in property <string> status;
    in property <float> progress;

    close-on-click: false;

    Rectangle {
        background: Palette.alternate-background;
        border-color: Palette.border;
        border-width: 1px;

        VerticalBox {
            alignment: center;

            Text {
                text: "Installing firmware, please wait.";
                horizontal-alignment: center;
            }

            ProgressIndicator {
                progress: progress;
            }

            Text {
                text: status;
                horizontal-alignment: center;
            }
        }
    }
}
