[package]
name = "pkg"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8"
cbc = "0.1"
context = { path = "../context" }
error = { path = "../error" }
memmap2 = "0.5"
pfs = { path = "../pfs" }
rsa = "0.7"
sha2 = "0.10"
util = { path = "../util" }
