[package]
name = "fs"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = { version = "2.3.1", features = ["serde"] }
serde = {version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "1.0"
