name: CI (Docs)
on:
  workflow_call:
jobs:
  build:
    name: Documentation
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build kernel documentation
      run: |
        import json
        import os
        from os.path import dirname
        from subprocess import Popen, PIPE
        import sys

        # Build.
        args = [
          'cargo', 'doc',
          '-p', 'obkrnl',
          '--all-features',
          '--document-private-items',
          '--no-deps',
          '--message-format', 'json-render-diagnostics'
        ]

        with Popen(args, env=dict(os.environ, RUSTDOCFLAGS='-D warnings'), stdout=PIPE) as proc:
          for line in proc.stdout:
            line = json.loads(line)
            reason = line['reason']
            if reason == 'build-finished':
              if line['success']:
                break
              else:
                sys.exit(1)
            elif reason == 'compiler-artifact':
              if line['target']['name'] == 'obkrnl':
                out = dirname(line['filenames'][0])

        # Set docs location.
        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
          print(f'location={out}', file=f)
      shell: python
      id: kernel
    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ steps.kernel.outputs.location }}
