name: CI (Docs)
on:
  workflow_call:
jobs:
  build:
    name: Documentation
    runs-on: ubuntu-24.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Install system packages
      run: |
        sudo apt-get update
        sudo apt-get install -y mkdocs
    - name: Disable PEP 668
      run: pip config set global.break-system-packages true
    - name: Install Python packages
      run: pip install mdx_truly_sane_lists
    - name: Update Rust
      run: rustup update stable
    - name: Build MkDocs
      run: mkdocs build
    - name: Build Kernel APIs
      run: |
        cargo doc -p obkrnl --all-features --document-private-items --no-deps
        mv target/doc site/crates
    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: site
