name: CI (Website)
on:
  workflow_call:
jobs:
  build:
    name: Website
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Install Material for MkDocs
      run: pip install mkdocs-material
    - name: Build
      run: mkdocs build --strict --site-dir dist
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist
