name: Development Build
on:
  push:
    branches:
    - main
concurrency: dev-${{ github.ref }}
jobs:
  build-windows:
    name: Build
    uses: ./.github/workflows/ci-windows.yml
  build-linux:
    name: Build
    uses: ./.github/workflows/ci-linux.yml
  build-mac:
    name: Build
    uses: ./.github/workflows/ci-mac.yml
  housekeep:
    name: Housekeep
    runs-on: ubuntu-latest
    steps:
    - name: Install Node packages
      run: sudo npm install -g octokit
    - name: Update PRs
      run: |
        import { Octokit } from 'octokit';

        const octokit = new Octokit({ auth: '${{ secrets.GITHUB_TOKEN }}' });
        const owner = '${{ github.event.repository.owner.login }}';
        const repo = '${{ github.event.repository.name }}';
        const resp = await octokit.request('GET /repos/{owner}/{repo}/pulls', {
          owner,
          repo,
          base: '${{ github.ref_name }}',
          sort: 'updated',
          direction: 'desc',
          per_page: 100,
        });

        for (const pull of resp.data) {
          await octokit.request('POST /repos/{owner}/{repo}/issues/{issue_number}/labels', {
            owner,
            repo,
            issue_number: pull.number,
            labels: ['B-out-of-date'],
          });
        }
      shell: node --experimental-default-type=module {0}
