name: Development Build
on:
  push:
    branches:
    - main
concurrency: dev-${{ github.ref }}
jobs:
  build-windows:
    name: Build
    uses: ./.github/workflows/ci-windows.yml
  build-linux:
    name: Build
    uses: ./.github/workflows/ci-linux.yml
  build-mac-intel:
    name: Build
    uses: ./.github/workflows/ci-mac.yml
    with:
      name: Mac Intel
      macos: macos-12
      kernel-target: x86_64-unknown-none
      artifact-name: obliteration-mac-intel
  build-mac-m1:
    name: Build
    uses: ./.github/workflows/ci-mac.yml
    with:
      name: Mac M1
      macos: macos-14
      kernel-target: aarch64-unknown-none-softfloat
      artifact-name: obliteration-mac-m1
  pr:
    name: Update PRs
    runs-on: ubuntu-latest
    steps:
    - name: Install Python modules
      run: pip install PyGithub
    - name: Update PRs
      run: |
        from datetime import datetime, timezone
        from github import Auth, Github

        now = datetime.now(timezone.utc)
        gh = Github(auth=Auth.Token("${{ secrets.GITHUB_TOKEN }}"))
        repo = gh.get_repo("${{ github.repository }}")

        for pull in repo.get_pulls("open", "updated", "desc", "${{ github.ref_name }}"):
          if (now - pull.updated_at).days > 30:
            break
          ready = False
          for label in pull.labels:
            if label.name == "S-ready":
              ready = True
          if ready:
            print(f"Removing S-ready from {pull.title}")
            pull.remove_from_labels("S-ready")
      shell: python
