name: Development Build
on:
  push:
    branches:
    - main
concurrency: dev-${{ github.ref }}
jobs:
  windows:
    name: Windows Build
    uses: ./.github/workflows/ci-windows.yml
  linux:
    name: Linux Build
    uses: ./.github/workflows/ci-linux.yml
  mac:
    name: Mac Build
    uses: ./.github/workflows/ci-mac.yml
