name: PR Post Build
on:
  workflow_run:
    workflows: [PR Build]
    types:
    - completed
jobs:
  postbuild:
    name: Update PR
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
    - name: Install Python modules
      run: pip install PyGithub
    - name: Update PR
      run: |
        from github import Auth, Github
        import json

        event = json.loads('${{ toJSON(github.event) }}')
        gh = Github(auth=Auth.Token("${{ secrets.GITHUB_TOKEN }}"))
        repo = gh.get_repo("${{ github.repository }}")

        for pull in event["workflow_run"]["pull_requests"]:
          author = pull["head"]["repo"]["name"]
          head = pull["head"]["sha"]
          cmp = repo.compare(pull["base"]["ref"], f"{author}:{head}")

          if cmp.status != "behind":
            pull = repo.get_pull(pull["number"])
            ready = False
            for label in pull.labels:
              if label.name == "S-ready":
                ready = True
            if not ready:
              pull.add_to_labels("S-ready")
      shell: python
